# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-13 07:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredCourse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('edx_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('org', models.CharField(max_length=255)),
                ('run', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'proctoring_proctoredcourse',
                'verbose_name': 'Proctored course',
            },
        ),
        migrations.CreateModel(
            name='ProctoredCourseProctoringService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_services', to='edx_proctoring.ProctoredCourse')),
            ],
            options={
                'db_table': 'proctoring_proctoredcourseproctoringservice',
                'verbose_name': 'Proctoring service',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('content_id', models.CharField(db_index=True, max_length=255)),
                ('external_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('exam_name', models.TextField()),
                ('time_limit_mins', models.IntegerField()),
                ('due_date', models.DateTimeField(null=True)),
                ('is_proctored', models.BooleanField(default=False)),
                ('is_practice_exam', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('hide_after_due', models.BooleanField(default=False)),
                ('backend', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'proctoring_proctoredexam',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamReviewPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('review_policy', models.TextField(default=b'')),
            ],
            options={
                'db_table': 'proctoring_proctoredexamreviewpolicy',
                'verbose_name': 'Proctored exam review policy',
                'verbose_name_plural': 'Proctored exam review policies',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamReviewPolicyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('original_id', models.IntegerField(db_index=True)),
                ('review_policy', models.TextField()),
            ],
            options={
                'db_table': 'proctoring_proctoredexamreviewpolicyhistory',
                'verbose_name': 'proctored exam review policy history',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamSoftwareSecureComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start_time', models.IntegerField()),
                ('stop_time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('comment', models.TextField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattemptcomment',
                'verbose_name': 'proctored exam software secure comment',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamSoftwareSecureReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attempt_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('review_status', models.CharField(max_length=255)),
                ('raw_data', models.TextField()),
                ('video_url', models.TextField()),
            ],
            options={
                'db_table': 'proctoring_proctoredexamsoftwaresecurereview',
                'verbose_name': 'Proctored exam software secure review',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamSoftwareSecureReviewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attempt_code', models.CharField(db_index=True, max_length=255)),
                ('review_status', models.CharField(max_length=255)),
                ('raw_data', models.TextField()),
                ('video_url', models.TextField()),
            ],
            options={
                'db_table': 'proctoring_proctoredexamsoftwaresecurereviewhistory',
                'verbose_name': 'Proctored exam review archive',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAllowance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentallowance',
                'verbose_name': 'proctored allowance',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAllowanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('allowance_id', models.IntegerField()),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentallowancehistory',
                'verbose_name': 'proctored allowance history',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('last_poll_timestamp', models.DateTimeField(null=True)),
                ('last_poll_ipaddr', models.CharField(max_length=32, null=True)),
                ('attempt_code', models.CharField(db_index=True, max_length=255, null=True)),
                ('external_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('allowed_time_limit_mins', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=64)),
                ('taking_as_proctored', models.BooleanField(default=False, verbose_name=b'Taking as Proctored')),
                ('is_sample_attempt', models.BooleanField(default=False, verbose_name=b'Is Sample Attempt')),
                ('student_name', models.CharField(max_length=255)),
                ('review_policy_id', models.IntegerField(null=True)),
                ('is_status_acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempt',
                'verbose_name': 'proctored exam attempt',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptCustom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attempt_id', models.IntegerField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('attempt_code', models.CharField(db_index=True, max_length=255, null=True)),
                ('external_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('allowed_time_limit_mins', models.IntegerField()),
                ('status', models.CharField(max_length=64)),
                ('taking_as_proctored', models.BooleanField(default=False)),
                ('is_sample_attempt', models.BooleanField(default=False)),
                ('student_name', models.CharField(max_length=255)),
                ('review_policy_id', models.IntegerField(null=True)),
                ('last_poll_timestamp', models.DateTimeField(null=True)),
                ('last_poll_ipaddr', models.CharField(max_length=32, null=True)),
                ('service', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattemptcustom',
                'verbose_name': 'proctored exam attempt custom',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attempt_id', models.IntegerField(null=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('attempt_code', models.CharField(db_index=True, max_length=255, null=True)),
                ('external_id', models.CharField(db_index=True, max_length=255, null=True)),
                ('allowed_time_limit_mins', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=64)),
                ('taking_as_proctored', models.BooleanField(default=False)),
                ('is_sample_attempt', models.BooleanField(default=False)),
                ('student_name', models.CharField(max_length=255)),
                ('review_policy_id', models.IntegerField(null=True)),
                ('last_poll_timestamp', models.DateTimeField(null=True)),
                ('last_poll_ipaddr', models.CharField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempthistory',
                'verbose_name': 'proctored exam attempt history',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptUserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('user_agent', models.TextField()),
                ('ip_address', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempt_usersession',
                'verbose_name': 'proctored exam attempt user session',
            },
        ),
        migrations.CreateModel(
            name='UsersWithSpecialPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_users_with_special_permissions',
                'verbose_name': 'user with special permissions',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamParams',
            fields=[
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proctored_exam_params', serialize=False, to='edx_proctoring.ProctoredExam')),
                ('updated', models.NullBooleanField(default=False)),
                ('service', models.CharField(max_length=255, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('start', models.DateTimeField(null=True)),
                ('visible_to_staff_only', models.NullBooleanField(default=False)),
                ('exam_review_checkbox', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'db_table': 'proctoring_proctoredexam_params',
                'verbose_name': 'proctored exam params',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptHistoryProctoringService',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proctoring_service', serialize=False, to='edx_proctoring.ProctoredExamStudentAttemptHistory')),
                ('service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempthistory_proctoringservice',
                'verbose_name': 'proctored exam attempt history proctoring service',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptProctoringService',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proctoring_service', serialize=False, to='edx_proctoring.ProctoredExamStudentAttempt')),
                ('service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempt_proctoringservice',
                'verbose_name': 'proctored exam attempt proctoring service',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptStopReason',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stop_reason', serialize=False, to='edx_proctoring.ProctoredExamStudentAttempt')),
                ('reason', models.TextField()),
                ('proctor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempt_stopreason',
                'verbose_name': 'proctored exam attempt stop reason',
            },
        ),
        migrations.AddField(
            model_name='proctoredexamstudentattemptusersession',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExamStudentAttempt'),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentattempthistory',
            name='proctored_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentattempthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentattemptcustom',
            name='proctored_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentattemptcustom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentattempt',
            name='proctored_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentallowancehistory',
            name='proctored_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentallowancehistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentallowance',
            name='proctored_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamstudentallowance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamsoftwaresecurereviewhistory',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamsoftwaresecurereviewhistory',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamsoftwaresecurereviewhistory',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamsoftwaresecurereview',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamsoftwaresecurereview',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamsoftwaresecurereview',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamsoftwaresecurecomment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExamSoftwareSecureReview'),
        ),
        migrations.AddField(
            model_name='proctoredexamreviewpolicyhistory',
            name='proctored_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamreviewpolicyhistory',
            name='set_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proctoredexamreviewpolicy',
            name='proctored_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam'),
        ),
        migrations.AddField(
            model_name='proctoredexamreviewpolicy',
            name='set_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='proctoredexam',
            unique_together=set([('course_id', 'content_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='proctoredexamstudentattemptusersession',
            unique_together=set([('attempt', 'session_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='proctoredexamstudentattempt',
            unique_together=set([('user', 'proctored_exam')]),
        ),
        migrations.AlterUniqueTogether(
            name='proctoredexamstudentallowance',
            unique_together=set([('user', 'proctored_exam', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='proctoredcourseproctoringservice',
            unique_together=set([('course', 'name')]),
        ),
    ]
