# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-06-02 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edx_proctoring', '0002_proctoredexamstudentattemptcustom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctoredexamstudentattemptcustom',
            name='allowed_time_limit_mins',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
