# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-21 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0009_proctoredexamreviewpolicy_remove_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredCourse',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('edx_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('org', models.CharField(max_length=255)),
                ('run', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'proctoring_proctoredcourse',
                'verbose_name': 'Proctored course',
            },
        ),
        migrations.CreateModel(
            name='ProctoredCourseProctoringService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_services', to='edx_proctoring.ProctoredCourse')),
            ],
            options={
                'db_table': 'proctoring_proctoredcourseproctoringservice',
                'verbose_name': 'Proctoring service',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamParams',
            fields=[
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proctored_exam_params', serialize=False, to='edx_proctoring.ProctoredExam')),
                ('updated', models.NullBooleanField(default=False)),
                ('service', models.CharField(max_length=255, null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('start', models.DateTimeField(null=True)),
                ('visible_to_staff_only', models.NullBooleanField(default=False)),
                ('exam_review_checkbox', jsonfield.fields.JSONField(default={})),
            ],
            options={
                'db_table': 'proctoring_proctoredexam_params',
                'verbose_name': 'proctored exam params',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptHistoryProctoringService',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proctoring_service', serialize=False, to='edx_proctoring.ProctoredExamStudentAttemptHistory')),
                ('service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempthistory_proctoringservice',
                'verbose_name': 'proctored exam attempt history proctoring service',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptProctoringService',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='proctoring_service', serialize=False, to='edx_proctoring.ProctoredExamStudentAttempt')),
                ('service', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempt_proctoringservice',
                'verbose_name': 'proctored exam attempt proctoring service',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptStopReason',
            fields=[
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stop_reason', serialize=False, to='edx_proctoring.ProctoredExamStudentAttempt')),
                ('reason', models.TextField()),
                ('proctor', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempt_stopreason',
                'verbose_name': 'proctored exam attempt stop reason',
            },
        ),
        migrations.CreateModel(
            name='ProctoredExamStudentAttemptUserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('user_agent', models.TextField()),
                ('ip_address', models.CharField(max_length=255)),
                ('hidden', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExamStudentAttempt')),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentattempt_usersession',
                'verbose_name': 'proctored exam attempt user session',
            },
        ),
        migrations.CreateModel(
            name='UsersWithSpecialPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='special_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_users_with_special_permissions',
                'verbose_name': 'user with special permissions',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proctoredexamstudentattemptusersession',
            unique_together=set([('attempt', 'session_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='proctoredcourseproctoringservice',
            unique_together=set([('course', 'name')]),
        ),
    ]
